-- Git commands
VKSN("<leader>gs", vim.cmd.Git, { desc = "git status" })
VKSN("<leader>gaa", ":Git add .<CR>", { desc = "git add ." })
VKSN("<leader>gaf", ":Git add ", { desc = "git add - specific files" })
VKSN("<leader>gcc", ":Git commit -m ''<Left>", { desc = "git commit - short message" })
VKSN("<leader>gcm", ":Git commit ", { desc = "git commit - page message" })
VKSN("<leader>gca", ":Git commit --amend --no-edit<CR>", { desc = "git commit ammend" })
VKSN("<leader>gco", ":Git checkout ", { desc = "git checkout" })
VKSN("<leader>gcO", ":Git checkout origin/", { desc = "git checkout origin " })
VKSN("<leader>gcf", function()
    vim.cmd("Git stash")
    vim.cmd("Git fecth")
    vim.cmd("Git checkout main")
    vim.cmd("Git reset --hard origin/main")
end, { desc = "Force sync with main" })
VKSN("<leader>gcl", ":Git clean -f ", { desc = "git clean" })
VKSN("<leader>gps", ":Git push<CR>", { desc = "git push" })
VKSN("<leader>gpl", ":Git pull<CR>", { desc = "git pull" })

-- Git tools
VKSN("<leader>go", ":GBrowse<CR>", { desc = "Open on Browser" })
VKSN("<leader>gb", ":Git blame<CR>", { desc = "Git blame" })
VKSN("<leader>gd", ":DiffviewOpen<CR>", { desc = "Open Diffview Tool" })
VKSN("<leader>gD", ":DiffviewOpen origin/", { desc = "Open Diffview Tool on commit" })
VKSN("<leader>gm", ":Git mergetool<CR>", { desc = "Git Merge Tool" })
VKSN("<leader>gh", ":Agit<CR>", { desc = "Git History - Agit" })
VKSN("<leader>gH", ":DiffviewFileHistory<CR>", { desc = "Git History - Diffview" })
VKSN("<leader>gf", ":AgitFile<CR>", { desc = "File Git History - Agit" })
VKSN("<leader>gF", ":DiffviewFileHistory %<CR>", { desc = "File Git History - Diffview" })
VKSN("<leader>gl", "<cmd>LazyGit<cr>", { desc = "Open Lazygit" })

WHICH_KEY({ ["<leader>g"] = { name = "+git" } })
