apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotfiles
  annotations:
    github.com/project-slug: henriquemeca/dotfiles
spec:
  type: other
  lifecycle: unknown
  owner: guests
