prSections:
  - title: Review Pending
    filters: is:open -is:draft -reviewed-by:@me repo:Kanastra-Tech/cloud-composer-repo repo:Kanastra-Tech/python-report-builder -author:@me
  - title: Involved
    filters: is:open repo:Kanastra-Tech/cloud-composer-repo repo:Kanastra-Tech/python-report-builder involves:@me -author:@me -is:draft
  - title: MyPRs
    filters: is:open author:@me repo:Kanastra-Tech/cloud-composer-repo repo:Kanastra-Tech/python-report-builder
    #layout:
    #author:
    #hidden: true
    # width: <number of columns>
    # grow: <bool> this will make the column grow in size
    #limit: 50 # optional limit of rows fetched for this section
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Subscribed
    filters: is:open -author:@me repo:microsoft/vscode repo:dlvhdr/gh-dash
defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 10
        hidden: false
    # issues: same structure as prs
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true # wether to have the preview pane open by default
    width: 60 # width in columns
  refetchIntervalMinutes: 30 # will refetch all sections every 30 minutes
repoPaths:
  Kanastra-Tech/cloud-composer-repo: ~/github/cloud-composer-repo
  Kanastra-Tech/python-report-builder: ~/github/python-report-builder
keybindings:
  prs:
    - key: l
      command: >
        tmux new-window -n {{.HeadRefName}} -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":Octo pr edit {{.PrNumber}}"
        '
