prSections:
  - title: Review Pending - Composer
    filters: is:open -reviewed-by:@me repo:Kanastra-Tech/cloud-composer-repo
  - title: Involved - Composer
    filters: is:open repo:Kanastra-Tech/cloud-composer-repo involves:@me
  - title: MyPRs - Composer
    filters: is:open author:@me repo:Kanastra-Tech/cloud-composer-repo
    #layout:
    #author:
    #hidden: true
    # width: <number of columns>
    # grow: <bool> this will make the column grow in size
    #limit: 50 # optional limit of rows fetched for this section
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Subscribed
    filters: is:open -author:@me repo:microsoft/vscode repo:dlvhdr/gh-dash
defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 10
        hidden: false
    # issues: same structure as prs
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true # wether to have the preview pane open by default
    width: 60 # width in columns
  refetchIntervalMinutes: 30 # will refetch all sections every 30 minutes
repoPaths:
  Kanastra-Tech/cloud-composer-repo: ~/github/cloud-composer-repo
keybindings:
  prs:
    - key: c
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":Octo pr edit {{.PrNumber}}"
        '
      #command: >
      #cd {{.RepoPath}} &&
      #code . &&
      #gh pr checkout {{.PrNumber}}
    #- key: v

#theme: # optional, see more info below
#pager:
#diff: less # or delta for example
