
[[Snippets]]
  Description = "File Navigator"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "yazi"

[[Snippets]]
  Description = "Disk usage"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "ncdu"

[[Snippets]]
  Description = "Docker Kafka"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "docker compose -f ./docker-compose.kafka.yml <action=up>"

[[Snippets]]
  Description = "Find duplicate entries in executive report df"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "echo \"self.df[self.df.duplicated(subset=[*index, columns], keep=False)]\""
