[[Snippets]]
  Description = "File Navigator"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "ranger"

[[Snippets]]
  Description = "Disk usage"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "ncdu"

[[Snippets]]
  Description = "Docker Kafka"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "docker compose -f ./docker-compose.kafka.yml <action=up>"
