
[[Snippets]]
  Description = "File Navigator"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "yazi"

[[Snippets]]
  Description = "Disk usage"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "ncdu"

[[Snippets]]
  Description = "Docker Kafka"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "docker compose -f ./docker-compose.kafka.yml <action=up>"

[[Snippets]]
  Description = "Find duplicate entries in executive report df"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "echo \"self.df[self.df.duplicated(subset=[*index, columns], keep=False)]\""

[[Snippets]]
  Description = "List available GH Actions"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "act --list"

[[Snippets]]
  Description = "Load laravel php modules"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "composer dump-autoload"

[[Snippets]]
  Description = "Clean hub schema"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "docker compose run --rm -e XDEBUG_MODE=coverage php php artisan schema:dump"

[[Snippets]]
  Description = "Disable containers restart"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "docker ps -q | xargs -I {} docker update --restart=no {}"

[[Snippets]]
  Description = "Generate UUID lowered"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "uuidgen | tr '[:upper:]' '[:lower:]'"

[[Snippets]]
  Description = "Generate UUDI upper"
  Filename = "/Users/henriquebrito/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "uuidgen"
